### ISSUE TITLE
warn org.bukkit.World.getChunkAt(org.bukkit.Location

### ISSUE THREAD

**Issue by joaoespanhol** [ajgeiss0702/ajLeaderboards#20]
[07:52:34 WARN]: [ajLeaderboards] An error occurred while loading a sign:
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getChunkAt(org.bukkit.Location)" because the return value of "org.bukkit.Location.getWorld()" is null
        at org.bukkit.Location.getChunk(Location.java:123) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at us.ajg0702.leaderboards.displays.signs.BoardSign.<init>(BoardSign.java:37) ~[ajLeaderboards-2.7.0.jar:?]
        at us.ajg0702.leaderboards.displays.signs.BoardSign.deserialize(BoardSign.java:141) ~[ajLeaderboards-2.7.0.jar:?]
        at us.ajg0702.leaderboards.displays.signs.SignManager.reload(SignManager.java:63) ~[ajLeaderboards-2.7.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.jar:git-Paper-8]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.20.jar:git-Paper-8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1114) ~[paper-1.20.jar:git-Paper-8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.20.jar:git-Paper-8]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

i am use paper

**Comment by ajgeiss0702** [comment]
This is not the place to get support

**Comment by ajgeiss0702** [comment]
This is not the place to get support
