### ISSUE TITLE
Error with 1.20.2 + ajLeaderboard 2.8.0 and PartyGames 6.6.7

### ISSUE THREAD

**Issue by CloudeLecaw** [ajgeiss0702/ajLeaderboards#25]
We used  ajLeaderboard to show the wins of PartyGames in the board.
in 1.20.1 it works fine. but in 1.20.2 i got this error.
im not sure if its related from aJLeaderboards or from PartyGames so i wrote it here too

```
[19:09:10] [Server thread/WARN]: [ajLeaderboards] Placeholder %partygames_wins% for player Cloude_Lecaw threw an error:
java.lang.NullPointerException: Cannot read field "wins" because "<local3>" is null
	at me.wazup.partygames.placeholderapi.PlaceholderAPIHooks.onPlaceholderRequest(PlaceholderAPIHooks.java:76) ~[PartyGames_6.6.7.jar:?]
	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32) ~[PlaceholderAPI_2.11.5-Build182.jar:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI_2.11.5-Build182.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI_2.11.5-Build182.jar:?]
	at us.ajg0702.leaderboards.cache.Cache.updateStat(Cache.java:493) ~[ajLeaderboards_2.8.0.jar:?]
	at us.ajg0702.leaderboards.cache.Cache.updatePlayerStats(Cache.java:447) ~[ajLeaderboards_2.8.0.jar:?]
	at us.ajg0702.leaderboards.Listeners.onQuit(Listeners.java:48) ~[ajLeaderboards_2.8.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1174.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-226]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-226]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-226]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:594) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:579) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2065) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2045) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2032) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:837) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:260) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-226]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by ajgeiss0702** [comment]
`Placeholder %partygames_wins% for player Cloude_Lecaw threw an error`
