### ISSUE TITLE
Error create leaderboards

### ISSUE THREAD

**Issue by steam9w** [ajgeiss0702/ajLeaderboards#28]
Extension - Statistic
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#statistic

Every time I try to create /ajlb add %statistic_mine_block%
I get the error:

[03:44:58] [Craft Scheduler Thread - 157/WARN]: [ajLeaderboards] Plugin ajLeaderboards v2.8.0 generated an exception while executing task 452
java.lang.NullPointerException: The supplied Material does not have a corresponding statistic
        at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[commons-lang3-3.5.jar:3.5]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.getStatistic(CraftPlayer.java:708) ~[CraftPlayer.class:git-CatServer-1.12.2-58b2eb6]
        at com.extendedclip.papi.expansion.mcstatistics.StatisticsExpansion.calculateTotal(StatisticsExpansion.java:286) ~[?:?]
        at com.extendedclip.papi.expansion.mcstatistics.StatisticsExpansion.onRequest(StatisticsExpansion.java:84) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[?:?]
        at us.ajg0702.leaderboards.LeaderboardPlugin.validatePlaceholder(LeaderboardPlugin.java:450) ~[?:?]
        at us.ajg0702.leaderboards.commands.main.subcommands.Add.lambda$execute$0(Add.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-58b2eb6]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-58b2eb6]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_391]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_391]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_391]

**Comment by ajgeiss0702** [comment]
This is not the place to get support
