### ISSUE TITLE
Error when starting the server

### ISSUE THREAD

**Issue by WarmRhombus** [ajgeiss0702/ajLeaderboards#31]
[15:11:29 WARN]: [ajLeaderboards] Task #1116 for ajLeaderboards v2.9.0 generated an exception
java.lang.IllegalArgumentException: The skull profile is missing a name or textures!
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar%23151!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile.validateSkullProfile(CraftPlayerProfile.java:39) ~[forge-1.20.1-47.3.1
-universal.jar%23217!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftSkull.setOwnerProfile(CraftSkull.java:123) ~[forge-1.20.1-47.3.1-universal.jar%23217!/
:?]
        at us.ajg0702.leaderboards.nms.nms19.HeadUtils19.lambda$setHeadBlock$0(HeadUtils19.java:69) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[forge-1.20.1-47.3.1-universal.jar%23217!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:416) ~[forge-1.20.1-47.3.1-unive
rsal.jar%23217!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1135) ~[server-1.20.1-20230612.114412-srg.jar%23212!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:349) ~[server-1.20.1-20230612.114412-srg.jar%23212!/:
?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1074) ~[server-1.20.1-20230612.114412-srg.jar%23212!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:904) ~[server-1.20.1-20230612.114412-srg.jar%23212!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23212!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by ajgeiss0702** [comment]
This is not the place to get support
