### ISSUE TITLE
mysql problem (8.0.30+) Failed to initialize pool: Unknown system variable 'tx_isolation'

### ISSUE THREAD

**Issue by SilentX88** [ajgeiss0702/ajLeaderboards#6]
The plugin won't start, getting error: Failed to initialize pool: Unknown system variable 'tx_isolation'

MySql version:
MySQL  Ver 8.0.30-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))

```
[06:26:22] [Server thread/INFO]: [ajLeaderboards] Enabling ajLeaderboards v2.6.2
[06:26:22] [Server thread/INFO]: [ajLeaderboards] Using MySQL for board cache. (mysql)
[06:26:22] [Server thread/ERROR]: Error occurred while enabling ajLeaderboards v2.6.2 (Is it up to date?)
us.ajg0702.leaderboards.libs.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unknown system variable 'tx_isolation'
	at us.ajg0702.leaderboards.libs.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:595) ~[?:?]
	at us.ajg0702.leaderboards.libs.hikari.pool.HikariPool.checkFailFast(HikariPool.java:574) ~[?:?]
	at us.ajg0702.leaderboards.libs.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
	at us.ajg0702.leaderboards.libs.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
	at us.ajg0702.leaderboards.cache.methods.MysqlMethod.init(MysqlMethod.java:55) ~[?:?]
	at us.ajg0702.leaderboards.cache.Cache.<init>(Cache.java:99) ~[?:?]
	at us.ajg0702.leaderboards.LeaderboardPlugin.onEnable(LeaderboardPlugin.java:167) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
Caused by: java.sql.SQLException: Unknown system variable 'tx_isolation'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1474) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.getTransactionIsolation(ConnectionImpl.java:3198) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at us.ajg0702.leaderboards.libs.hikari.pool.PoolBase.checkDefaultIsolation(PoolBase.java:479) ~[?:?]
	at us.ajg0702.leaderboards.libs.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:442) ~[?:?]
	at us.ajg0702.leaderboards.libs.hikari.pool.PoolBase.setupConnection(PoolBase.java:410) ~[?:?]
	at us.ajg0702.leaderboards.libs.hikari.pool.PoolBase.newConnection(PoolBase.java:363) ~[?:?]
	at us.ajg0702.leaderboards.libs.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
	at us.ajg0702.leaderboards.libs.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[?:?]
	at us.ajg0702.leaderboards.libs.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[?:?]
	... 16 more
[06:26:22] [Server thread/INFO]: [ajLeaderboards] Disabling ajLeaderboards v2.6.2
[06:26:22] [Server thread/INFO]: [ajLeaderboards] Killing remaining workers
[06:26:22] [Server thread/INFO]: [ajLeaderboards] Remaining workers killed
[06:26:22] [Server thread/INFO]: [ajLeaderboards] ajLeaderboards v2.6.2 disabled.
```

**Comment by ajgeiss0702** [comment]
This is not the place to get support
